name: "[C]ontinuous [I]ntegration"

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  PYRIGHT_PYTHON_FORCE_VERSION: latest

permissions:
  checks: write
  contents: read
  pull-requests: write
  security-events: write

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main

      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main
      - uses: percebus/github-actions-pipx/.github/actions/pipx_install@main

      - uses: percebus/github-actions-poetry/.github/actions/self_add_plugins@main
      - uses: percebus/github-actions-poetry/.github/actions/install@main

      - name: pip install .
        run: pip install .

      - uses: percebus/github-actions-pip/.github/actions/freeze@main

      # TODO
      # - name: pypyr lint
      #   run: pipx run -- pypyr lint stats=True

      - name: pypyr test
        run: pipx run -- pypyr ci lint=False

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          tests_name: "" # disables actions/test-reporter. It doesn't like pytest's junit format
          files_pattern: test-junit.xml
